name: Build and publish app
on:
  push:

env:
  PROJECT_ID: ${{ secrets.G_PROJECT_ID }}
  REGISTRY: eu.gcr.io
  IMAGE: ${{ github.event.repository.name }}

jobs:
  build-publish:
    name: Build, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build docker image
        run: |-
          docker build \
            --tag "$REGISTRY/$PROJECT_ID/$IMAGE:build-$GITHUB_RUN_NUMBER" \
            --tag "$REGISTRY/$PROJECT_ID/$IMAGE:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg GITHUB_RUN_NUMBER="$GITHUB_RUN_NUMBER" \
            -f Dockerfile \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish docker image
        run: |-
          docker push "$REGISTRY/$PROJECT_ID/$IMAGE:latest"
